### PR TITLE
ffh-check-connection: initial commit

### PR DESCRIPTION
**Pull request by CodeFetch**
This commit adds a new package which can be used for scheduled
connectivity checks.

### CODE REVIEW

**Comment by CodeFetch** [comment]
@mweinelt Maybe it makes more sense to add the LICENSE file of Gluon into the base directory of this repository as the Gluon license (whatever it is) has no clear SPDX identifier.

**Comment by rotanid** [comment]
is this a newer version of #1930 ? 
what's your reasoning to not go with core idea #2228 ? do you intend to have your solution only in place until 2228 is implemented?

in any case, possible to merge here in community repo, maybe @lemoer wants to do it, he could endorse it as another person from ffh and has the rights to merge.

**Comment by CodeFetch** [comment]
@rotanid Yes, it's almost the same as #1930. Actually the code in #1930 worked out of the box besides a missing tonumber. I lost interest in #1930, because I didn't get any feedback on my basic question: Is this the way we want to handle it?

I don't go with the idea in https://github.com/freifunk-gluon/gluon/issues/2228, because we had the same discussion 2 years ago for the offline-ssid package. At that time it was decided that check-connection should use ICMP ping, because of the following reasons:
- it should allow to be configured with *global* ping targets so that even a connectivity failure in the backbone would be detected
- it should be completely mesh-protocol agnostic
- it should be a generic approach for doing connectivity checks (to also use it in e.g. scheduled-domain-switch, wifi-fallback-autoupdater etc.)

Now in https://github.com/freifunk-gluon/gluon/issues/2228 the same discussion was started again, but they seem to have forgotten all the initial goals and are now building something over-engineered which does not fulfill the purposes.

The reason they want to do it differently seems to be that ICMP pings are costly?! But that is not true at all. Doing a ping once a minute with a bigger collection of servers (e.g. from Freifunk communities) is negligible from a resource view. Ping was designed to do pings and batctl is not mesh-protocol-agnostic and is more costly. I felt they only did #2228, because they don't like me or something, because it does not make sense. I can't respond to #2228, because they blocked me from discussion there...

**Comment by CodeFetch** [comment]
I converted this to a draft as some people feel that pinging global hosts has a too high cost. While I do not agree about the cost I see the possibility to limit these pings by:
- In a first step only letting nodes with VPN connection do the ping check and adding a respondd provider to inform other nodes
- In the second step even further limiting the ping checks (in case of multiple nodes with VPN connections) by electing a leader using the RAFT protocol to do the ping check

For the second step I've outlined an idea a while ago to semantically segment the mesh network with a daemon called meshrealmd which uses RAFT to elect leaders for segments . That will take a while...

**Comment by AiyionPrime** [comment]
gluon/2245 was merged yesterday; it may make sense to take a look at it;
you might find opportunities to reduce some codebase of yours.

**Comment by maurerle** [comment]
It is now more than 3 years ago that this was active.

Use of `/var/gluon/state/has_default_gw4` as a connectivity check is currently used in `ffac-autoupdater-wifi-fallback` and `ffac-ssid-changer`.
So I am closing this PR now.

**Pull request closed without merging**
