### PR TITLE
ffac-ssid-changer: add refactored ssid-changer

### LINKED ISSUE #27: [suggestion] Add Offline-SSID-Changer using gluon has_default_gw
It would be very good to have an Offline-SSID-Changer package available here.
It should work with BATMAN_IV, BATMAN_V and babel

existing repos from single communities are:
- https://github.com/freifunk-kiel/gluon-ssid-notifier/
- #9  (mesh protocol agnostic)
- https://github.com/eulenfunk/packages/tree/v2020.1.x/gluon-ssid-changer
- https://github.com/ffac/gluon-ssid-changer/
- https://github.com/Freifunk-Nord/gluon-ssid-changer
- https://gitlab.freifunk-stuttgart.de/firmware/gluon-ssid-changer
- https://github.com/tecff/gluon-packages/tree/main/tecff-ssid-changer (supports has_default_gw and owe)

A [try to put something like this upstream](https://github.com/freifunk-gluon/gluon/pull/1649) failed, so I think it would be best to have this package here.

Recently gluon got a mesh-agnostic way to receive the online state and neighbours:
- https://github.com/freifunk-gluon/gluon/issues/2228

So it would be cool to have a package which relies on this functionality.

### PR DESCRIPTION
**Pull request by maurerle**
- use owe consideration from tecff
- use mesh agnostic has_default_gw4 (gluon-state-check)
- use latest changes
- only compatible with next gluon release fro master (probably v2023.1.1)

closes #27

### CODE REVIEW

**Comment by maurerle** [comment]
Due to relying on gluon-state-check, this is only compatible with v2022.1.x or greater.

Still @rubo77 @mmalte @adorfer @codefetch - as you are maintaining the packages mentioned in #27 I would like to get your input/review and raise your attention on merging this.

I tested it with v2022.1.4 gluon and it worked good - I did not yet test out the TQ_Limit (only working with BATMAN_IV) - but it did not change to prior implementations.

Also I have the question of licensing and if I should put the name of all involved somewhere?

**Comment by rubo77** [comment]
I would be pleased, if you mention my alias

**Comment by blocktrron** [comment]
@rubo77 do you mean you want to be credited in the package readme?

**Comment by rubo77** [comment]
Maybe an extra file CREDITS.md

**Comment by maurerle** [comment]
So as I don't want to step on anyones feet by adding packages I didn't write myself, I would like to add the License so that attribution is done correctly, I propose to add a LICENSE file containing the BSD-2-Clause License as its originally from here:
https://github.com/ffac/gluon-ssid-changer/blob/2019.1.x/LICENSE

with the following Clause:

`Copyright (c) 2023, Malte Möller, Jens Viisauksena, CCCFr, Ruben Barkow, Andreas Ziegler, Sven Eckelmann and Florian Maurer`

And also add the following to the Makefile
```
# SPDX-FileCopyrightText: 2023 Malte Möller, Jens Viisauksena, Ruben Barkow, Andreas Ziegler, Sven Eckelmann and Florian Maurer
# SPDX-License-Identifier: BSD-2-Clause
```

is everybody okay and happy with this? Would be cool if you can give a thumbs up or leave feedback.

Also mentioning @ecsv and @rotanid - as they also committed to this package

**Comment by mkg20001** [comment]
Can you fix the commit message. Otherwise this seems good for merge.

**Comment by maurerle** [comment]
I think it is better now?
So you can merge this :)

**Pull request merged**
