### PR TITLE
ffh-wifi-offline-ssid: initial commit

### PR DESCRIPTION
**Pull request by CodeFetch**
This commit adds a package to change the SSID if no internet connection is
available. It depends on ffh-check-connection.

This is based on https://github.com/freifunk-gluon/gluon/pull/1649

Still needs some testing and refactoring in ffh-check-connection. PR opened for reference now.

EDIT by rotanid: depends on https://github.com/freifunk-gluon/community-packages/pull/9

### CODE REVIEW

**Comment by CodeFetch** [comment]
It works besides that the permission for the /usr/sbin/ffh-wifi-offline-ssid file was not set executable. Any clue why?

**Comment by rotanid** [comment]
what i don't like is that it seems not possible to also handle "flakey" connections as offline, like with batman gateway TQ threshold in solutions like https://github.com/tecff/gluon-packages/tree/main/tecff-ssid-changer or https://github.com/ffac/gluon-ssid-changer or https://github.com/Freifunk-Nord/gluon-ssid-changer (which are all somehow related/similar)

**Comment by CodeFetch** [comment]
@rotanid 
1. It should be mesh-protocol agnostic.
2. When is a connection considered flaky? A connection with a TQ about 20 could still deliver ~5 Mbit/s with AC chipsets, but can't handle timing-critical streams like telephony. I think some internet is better than none and bad connections should be fixed by the node operators.

**Comment by awlx** [comment]
As we use BATMAN_V and have no TQ but throughput. I really love this is mesh protocol agnostic.

**Comment by rubo77** [comment]
Is this still working in gluon 2021.1.1?

**Comment by mkg20001** [comment]
Close? Update?

**Comment by rubo77** [comment]
Isn't this solved in
https://github.com/freifunk-gluon/community-packages/blob/master/ffac-ssid-changer/README.md

**Comment by maurerle** [comment]
As this is now more than 3 years ago, I will close this in favor of the ffac-ssid-changer.
I would rather adjust this, if improvements are needed, instead of adding an additional package with the same job.

**Pull request closed without merging**
