### PR TITLE
ci: add shell linting workflow

### PR DESCRIPTION
**Pull request by grische**
A proposal to add some shell linting as there are quite some shell scripts in this repository.

### CODE REVIEW

**Review by maurerle — APPROVED** [review]
As this affects more than the packages I am responsible off, I think at least someone else should be aware and approve this change?

I think it is quite good

**Comment by grische** [comment]
Yeah, this will cause a considerable amount of warnings/errors the next time someone touches a shell script. I can go ahead and fix (most of) them if needed beforehand.

**Comment by herbetom** [comment]
Is there a link where one can see which scripts (in which way) this will affect? I've got no idea wheter shellcheck is a fitting choice for this repo.

And yes, i think fixing those scripts should be done beforehand and not by the next person who finds themself in the unfortunate situation to trigger that workflow ;)

**Comment by grische** [comment]
Shellcheck helped me identify a range of bugs in the ssid-changer script, so I do think that it is a helpful addition in general.

You can run this command locally, that roughly does what the action does:
```
shellcheck $(find . -type f -print0 | xargs -0 awk 'FNR==1 && /^#!.*sh/ { print FILENAME }')
```

**Comment by maurerle** [comment]
I did run:

`shellcheck -f diff $(find . -type f ! -path './.git/*' -print0 | xargs -0 awk 'FNR==1 && /^#!.*sh/ { sub(/^.{2}/, "", FILENAME); print FILENAME }') | git apply`

to auto fix some issues - but most have to be solved manually.

There are still a lot here: `shellcheck $(find . -type f -print0 | xargs -0 awk 'FNR==1 && /^#!.*sh/ { print FILENAME }')`
I think some are quite verbose like 
` ^-- SC3014 (warning): In POSIX sh, == in place of = is undefined.`
`SC1091 (info): Not following: /lib/gluon/autoupdater/lib.sh was not specified as input`
`^-------^ SC2034 (warning): USE_PROCD appears unused. Verify use (or export if used externally).`

and the like.. I don't think that it is beneficial to have a lot of shellcheck workarounds though :D
Do you have a neat solution for this? @grische just ignore SC2034 for example?

**Comment by grische** [comment]
Added an exemplary PRs that fix the shellcheck issues in the ffac-ssid-changer package:
- https://github.com/freifunk-gluon/community-packages/pull/54
- https://github.com/freifunk-gluon/community-packages/pull/55

**Comment by grische** [comment]
Regarding ` ^-- SC3014 (warning): In POSIX sh, == in place of = is undefined.`, this is a real warning, as this does not work across multiple shells:

`ash`
```sh
X=1
[ $X = 1 ]
[ $X == 1 ]
ash: 3: [: 1: unexpected operator
```

`dash`
```sh
X=1
[ $X = 1 ]
[ $X == 1 ]
dash: 3: [: 1: unexpected operator
```

`ksh`, `bash` or `busybox sh`
```sh
X=1
[ $X = 1 ]
[ $X == 1 ]
```

Shellcheck has support for full bash, ksh and dash, but not the full set for `busybox sh`. It interprets `busybox sh` as ash and ash in turn as dash:
https://www.shellcheck.net/wiki/SC1071

**Comment by grische** [comment]
I opened an issue with shellcheck to see if it can be improved for our use-case here:
https://github.com/koalaman/shellcheck/issues/2865

**Comment by grische** [comment]
I opened PRs for all outstanding shellcheck issue and assigned it to the "suggested" reviewer from Github:

- https://github.com/freifunk-gluon/community-packages/pull/60
- https://github.com/freifunk-gluon/community-packages/pull/61
- https://github.com/freifunk-gluon/community-packages/pull/62
- https://github.com/freifunk-gluon/community-packages/pull/63
- https://github.com/freifunk-gluon/community-packages/pull/64
- https://github.com/freifunk-gluon/community-packages/pull/65
- https://github.com/freifunk-gluon/community-packages/pull/66
- https://github.com/freifunk-gluon/community-packages/pull/67
- https://github.com/freifunk-gluon/community-packages/pull/68
- https://github.com/freifunk-gluon/community-packages/pull/69

These PRs should address all shellcheck issues.

**Comment by grische** [comment]
@maurerle @herbetom @neocturne except the #61, all shellcheck issues should be resolved now and the CI passes at least on my local machine.

**Pull request merged**
